name: Unity Build

on:  
  push: { branches: [master] }


env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.1.7f1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'run unity build'
      uses: ncipollo/unity-action@master
      with: 
        license: ${{ secrets.UNITY_LICENSE }}
        mode: build
        build_method: BuildCommand.PerformBuild
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build.tar.gz
        path: Build/os_x
