name: Unity Build

on:  
  push: { branches: [master] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'run unity build'
      uses: ncipollo/unity-action@master
      with: 
        license: ${{ secrets.UNITY_LICENSE }}
        mode: build
        build_method: BuildCommand.PerformBuild
        projectPath: UnityGame
        username: ${{ secrets.UNITY_USERNAME }}
        password: ${{ secrets.UNITY_PASSWORD }}
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build.tar.gz
        path: Build/os_x
