name: Unity Build

on:  
  push: { branches: [master] }


env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: UnityGame/Library
          key: Library

      # # Test
      # - name: Run tests
      #   uses: webbertakken/unity-test-runner@v1.3
      #   with:
      #     unityVersion: 2020.1.7f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2020.1.7f1
          targetPlatform: WebGL
          projectPath: UnityGame

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
